import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 自动生成侧边栏 - 从 docs 文件夹结构自动识别
  mainSidebar: [
    'index', // 文档首页
    {
      type: 'category',
      label: '系统教程',
      collapsed: false, // 默认展开
      link: {
        type: 'generated-index',
        title: '系统教程',
        description: '操作系统使用技巧、配置指南和问题解决方案。涵盖 Windows、macOS、Linux 等主流系统。',
        slug: '/category/system-tutorial',
        keywords: ['系统', '操作系统', 'Windows', 'macOS', 'Linux'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'system-tutorial',
        },
      ],
    },
    {
      type: 'category',
      label: '软件教程',
      collapsed: false, // 默认展开
      link: {
        type: 'generated-index',
        title: '软件教程',
        description: '常用软件的详细使用教程，帮助你快速上手各类工具软件。包括网络工具、开发工具、办公软件等。',
        slug: '/category/software-tutorial',
        keywords: ['软件', '工具', 'VPN', '开发', '办公'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'software-tutorial',
        },
      ],
    },
    {
      type: 'category',
      label: '热门推荐',
      collapsed: false, // 默认展开
      link: {
        type: 'generated-index',
        title: '热门推荐',
        description: '最新、最受欢迎的工具和使用技巧推荐，定期更新。包括最新工具推荐、热门教程和实用技巧。',
        slug: '/category/hot-recommend',
        keywords: ['热门', '推荐', '工具', '技巧'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'hot-recommend',
        },
      ],
    },
  ],
};

export default sidebars;
